// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Locates git and reports its version and whether it meets the minimum. */
	checkGit: () => typedError<GitInfo, AppError>(__TAURI_INVOKE("check_git")),
	/**  Lists added repositories, most recently opened first. */
	listRepositories: () => __TAURI_INVOKE<RepositoryList>("list_repositories"),
	/**  Opens a folder picker and adds the chosen repository. `None` if the user cancelled. */
	addLocalRepository: () => typedError<{
	id: string,
	/**  Alias, or the folder name. */
	name: string,
	path: string,
	/**  The folder no longer exists (moved or deleted). */
	missing: boolean,
} | null, AppError>(__TAURI_INVOKE("add_local_repository")),
	/**  Removes a repository from the list. Files on disk are not touched. */
	removeRepository: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_repository", { id })),
	/**  Selects a repository and marks it recently opened. */
	selectRepository: (id: string) => typedError<Repository, AppError>(__TAURI_INVOKE("select_repository", { id })),
	/**  Working directory status for a repository. */
	getStatus: (repoId: string) => typedError<WorkingDirectoryStatus, AppError>(__TAURI_INVOKE("get_status", { repoId })),
	/**  Diff of a changed working-directory file. Unchanged if the file no longer has changes. */
	getWorkingDiff: (repoId: string, path: string) => typedError<FileDiff, AppError>(__TAURI_INVOKE("get_working_diff", { repoId, path })),
	/**  A page of commits reachable from HEAD, newest first. */
	getHistory: (repoId: string, skip: number, limit: number) => typedError<Commit[], AppError>(__TAURI_INVOKE("get_history", { repoId, skip, limit })),
	/**  Files changed by a commit. */
	getCommitFiles: (repoId: string, sha: string) => typedError<CommitFile[], AppError>(__TAURI_INVOKE("get_commit_files", { repoId, sha })),
	/**  Diff of one file within a commit. */
	getCommitDiff: (repoId: string, sha: string, path: string, oldPath: string | null) => typedError<FileDiff, AppError>(__TAURI_INVOKE("get_commit_diff", { repoId, sha, path, oldPath })),
	/**  Local and remote branches. */
	getBranches: (repoId: string) => typedError<BranchList, AppError>(__TAURI_INVOKE("get_branches", { repoId })),
	/**
	 *  Starts watching a repository for changes (emits `RepoChanged`). Replaces any previous watch.
	 *  Watching is best-effort: on failure the UI still refreshes on window focus.
	 */
	watchRepository: (repoId: string) => typedError<null, AppError>(__TAURI_INVOKE("watch_repository", { repoId })),
	/**  Stages (`staged = true`) or unstages the given changed files. */
	setStaged: (repoId: string, paths: string[], staged: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_staged", { repoId, paths, staged })),
	/**  Commits the staged changes. Returns the new commit's SHA. */
	commitChanges: (repoId: string, summary: string, description: string) => typedError<string, AppError>(__TAURI_INVOKE("commit_changes", { repoId, summary, description })),
	/**  The name and email git will record on commits in this repository. */
	getIdentity: (repoId: string) => typedError<Identity, AppError>(__TAURI_INVOKE("get_identity", { repoId })),
	/**
	 *  Saves name and email to the global git config. The UI calls this only after the user
	 *  explicitly confirms (CLAUDE.md rule 5).
	 */
	setGlobalIdentity: (name: string, email: string) => typedError<null, AppError>(__TAURI_INVOKE("set_global_identity", { name, email })),
	/**  Discards all changes to the given files. Current content goes to the OS trash first. */
	discardChanges: (repoId: string, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("discard_changes", { repoId, paths })),
	/**  Adds an untracked file (or all files with its extension) to the root `.gitignore`. */
	ignoreFile: (repoId: string, path: string, byExtension: boolean) => typedError<null, AppError>(__TAURI_INVOKE("ignore_file", { repoId, path, byExtension })),
	/**
	 *  Undoes the most recent commit if it is still `sha`, keeping its changes staged.
	 *  Returns the commit's message so the UI can restore it.
	 */
	undoCommit: (repoId: string, sha: string) => typedError<UndoneCommit, AppError>(__TAURI_INVOKE("undo_commit", { repoId, sha })),
	/**  Signed-in accounts (metadata only). */
	listAccounts: () => __TAURI_INVOKE<Account[]>("list_accounts"),
	/**  Checks that `server` is a reachable, trusted Forgejo server (sign-in step 2). */
	checkServer: (server: string) => typedError<ServerInfo, AppError>(__TAURI_INVOKE("check_server", { server })),
	/**  Verifies `token` with `GET /api/v1/user`, then saves the account and keychain entry. */
	signIn: (server: string, token: string) => typedError<Account, AppError>(__TAURI_INVOKE("sign_in", { server, token })),
	/**  Signs out: removes the account and deletes its token from the keychain. */
	signOut: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("sign_out", { id })),
	/**  Opens the server's "Applications" settings page, where the user creates a token. */
	openTokenSettings: (server: string) => typedError<null, AppError>(__TAURI_INVOKE("open_token_settings", { server })),
	/**  Delivers the user's answer to a prompt (`None` = cancelled, which stops the operation). */
	answerAuthPrompt: (promptId: string, answer: {
	username: string | null,
	secret: string,
} | null) => __TAURI_INVOKE<void>("answer_auth_prompt", { promptId, answer }),
	/**  Cancels a running fetch, pull or push. Unknown ids are ignored. */
	cancelOperation: (opId: string) => __TAURI_INVOKE<void>("cancel_operation", { opId }),
	/**  The toolbar sync button state for the current branch. */
	getSyncState: (repoId: string) => typedError<SyncState, AppError>(__TAURI_INVOKE("get_sync_state", { repoId })),
	/**
	 *  Runs a fetch, pull, push or publish. `op_id` (a UUID from the UI) identifies its progress
	 *  events and lets `cancel_operation` stop it.
	 */
	sync: (repoId: string, opId: string, request: SyncRequest) => typedError<null, AppError>(__TAURI_INVOKE("sync", { repoId, opId, request })),
	/**  How a typed branch name will be created (`"Fix pump"` → `"Fix-pump"`). Pure; no git call. */
	previewBranchName: (name: string) => __TAURI_INVOKE<string>("preview_branch_name", { name }),
	/**  Creates a branch from the current commit and switches to it. Local changes come along. */
	createBranch: (repoId: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("create_branch", { repoId, name })),
	/**  Switches to a local branch, or creates a tracking branch for a remote-only one. */
	switchBranch: (repoId: string, name: string, localChanges: LocalChanges) => typedError<null, AppError>(__TAURI_INVOKE("switch_branch", { repoId, name, localChanges })),
	/**  Deletes a local branch. Without `force`, fails with `BranchNotMerged` if it has unique commits. */
	deleteBranch: (repoId: string, name: string, force: boolean) => typedError<null, AppError>(__TAURI_INVOKE("delete_branch", { repoId, name, force })),
	/**  Changes Tenajlo saved when the user last left the current branch, if any. */
	getSavedChanges: (repoId: string) => typedError<{
	branch: string,
} | null, AppError>(__TAURI_INVOKE("get_saved_changes", { repoId })),
	/**  Re-applies the changes saved for the current branch. */
	restoreSavedChanges: (repoId: string) => typedError<null, AppError>(__TAURI_INVOKE("restore_saved_changes", { repoId })),
};

/** Events */
export const events = {
	authPromptRequested: makeEvent<AuthPromptRequested>("auth-prompt-requested"),
	gitProgress: makeEvent<GitProgress>("git-progress"),
	repoChanged: makeEvent<RepoChanged>("repo-changed"),
};

/* Types */
/**  Account metadata for the frontend. Never includes the token (CLAUDE.md rule 2). */
export type Account = {
	id: string,
	kind: AccountKind,
	baseUrl: string,
	login: string,
	displayName: string,
	avatarUrl: string | null,
};

/**  Kind of account. Only Forgejo for v1. */
export type AccountKind = "forgejo";

/**  Error shape sent to the frontend. Never contains secrets: `details` is redacted. */
export type AppError = {
	kind: AppErrorKind,
	/**  Set when `kind == Git`. */
	gitKind: GitErrorKind | null,
	/**  Plain-language message for non-Git-experts. */
	message: string,
	/**  Technical details shown behind "Details". */
	details: string | null,
};

/**  Broad category the UI uses to pick a dialog. */
export type AppErrorKind = "GitNotFound" | "GitUnsupported" | "GitTimedOut" | "GitCancelled" | "Git" | "UnknownRepository" | 
/**  A Forgejo server request failed (sign-in, repository list). */
"Server" | "UnknownAccount" | "Storage" | "InvalidInput" | "Internal";

/**  The user's answer. Flows UI → Rust only (CLAUDE.md rule 2). Debug output is redacted. */
export type AuthAnswer = {
	username: string | null,
	secret: string,
};

/**  Ask the user something on behalf of a running git operation. */
export type AuthPromptRequested = {
	promptId: string,
	repoId: string,
	opId: string,
	kind: PromptKind,
};

export type Branch = {
	/**  Short name: `main`, or `origin/main` for remote branches. */
	name: string,
	kind: BranchKind,
	/**  Remote name for remote branches. */
	remote: string | null,
	/**  Upstream (`origin/main`) for local branches that track one. */
	upstream: string | null,
	tip: string,
	isCurrent: boolean,
	/**  ISO 8601 date of the tip commit. */
	lastCommitDate: string,
};

export type BranchKind = "Local" | "Remote";

/**  Branches grouped the way the branch dropdown shows them. */
export type BranchList = {
	current: string | null,
	/**  Local branches, sorted by name (current included). */
	local: Branch[],
	/**  Remote branches with no local branch tracking them or sharing their name. */
	remoteOnly: Branch[],
};

/**  Branch information from `# branch.*` headers. */
export type BranchState = {
	/**  Current branch name; `None` when HEAD is detached. */
	name: string | null,
	/**  HEAD commit; `None` in a repository with no commits yet. */
	tip: string | null,
	upstream: string | null,
	ahead: number,
	behind: number,
	/**  An upstream is configured but no longer exists on the remote. */
	upstreamGone: boolean,
};

/**  One commit in the History list. */
export type Commit = {
	sha: string,
	shortSha: string,
	parents: string[],
	authorName: string,
	authorEmail: string,
	/**  Strict ISO 8601 with offset. */
	authorDate: string,
	summary: string,
	body: string,
};

/**  A file changed by a commit. */
export type CommitFile = {
	path: string,
	oldPath: string | null,
	kind: FileStatusKind,
};

export type DiffHunk = {
	/**  The full `@@ … @@ section` header line. */
	header: string,
	lines: DiffLine[],
};

export type DiffLine = {
	kind: DiffLineKind,
	/**  Line content without the +/-/space marker or line ending. */
	text: string,
	oldLine: number | null,
	newLine: number | null,
	/**  Followed by "\ No newline at end of file". */
	noNewline: boolean,
};

export type DiffLineKind = "Context" | "Add" | "Delete";

/**  One changed path. */
export type FileChange = {
	/**  Repo-relative path, `/`-separated. */
	path: string,
	/**  Original path for renames and copies. */
	oldPath: string | null,
	kind: FileStatusKind,
	staged: StagedState,
	/**  The path is a submodule (detected and shown only; spec §2). */
	submodule: boolean,
};

/**  A file's diff, ready to render. */
export type FileDiff = { type: "Text"; hunks: DiffHunk[] } | { type: "Binary" } | { type: "TooLarge" } | 
/**  No content changes (e.g. only the file mode changed). */
{ type: "Unchanged" };

/**  What happened to a file, as shown in the Changes list. */
export type FileStatusKind = "Untracked" | "Added" | "Modified" | "Deleted" | "Renamed" | "Copied" | "Conflicted";

/**  Typed classification of a failed git invocation. */
export type GitErrorKind = "AuthFailed" | "HostKeyUnknown" | "SshKeyRejected" | "PushRejected" | "PullDiverged" | "LocalChangesBlock" | "TlsUntrusted" | "HostUnreachable" | "MergeConflict" | "NotARepository" | 
/**  Folder owned by another user; git's `safe.directory` check refused it. */
"DubiousOwnership" | 
/**  `user.name` / `user.email` not configured. */
"IdentityMissing" | "BranchExists" | "BranchNotMerged" | "Unknown";

/**  Result of the startup git check, sent to the UI. */
export type GitInfo = {
	/**  Absolute path of the git executable in use. */
	path: string,
	version: GitVersion,
	minimum: GitVersion,
	/**  `version >= minimum`. */
	supported: boolean,
};

/**  Progress of a running remote operation. */
export type GitProgress = {
	repoId: string,
	opId: string,
	progress: Progress,
};

/**  A git version triple. Vendor suffixes (`.windows.1`, `(Apple Git-154)`) are dropped. */
export type GitVersion = {
	major: number,
	minor: number,
	patch: number,
};

/**  Effective identity for a repository (local, then global config). */
export type Identity = {
	name: string | null,
	email: string | null,
};

/**  What to do with uncommitted changes when switching (GitHub Desktop's two choices). */
export type LocalChanges = 
/**  Carry them to the target branch (fails if they would be overwritten). */
"Bring" | 
/**  Save them on the current branch and switch with a clean working directory. */
"Leave";

/**  One progress update, e.g. `Receiving objects: 45% (450/1000)`. */
export type Progress = {
	/**  `Receiving objects`, `Resolving deltas`, `Writing objects`, … */
	phase: string,
	percent: number | null,
	/**  Remainder after the percentage, e.g. `(450/1000), 1.20 MiB | 2.00 MiB/s`. */
	detail: string | null,
	/**  Reported by the server (`remote:` prefix). */
	remote: boolean,
};

/**  A prompt shown to the user. Never carries secrets. */
export type PromptKind = 
/**  Username and password/token for an HTTPS host (one dialog for git's two prompts). */
{ type: "Credentials"; host: string } | 
/**  Password only; the username is already known (e.g. `https://evan@host/…`). */
{ type: "Password"; host: string; username: string } | 
/**  Anything else git asks; shown verbatim. */
{ type: "Other"; prompt: string };

/**  Emitted (debounced) when files or git state in a watched repository change. */
export type RepoChanged = {
	repoId: string,
};

/**  A repository as shown in the UI. */
export type Repository = {
	id: string,
	/**  Alias, or the folder name. */
	name: string,
	path: string,
	/**  The folder no longer exists (moved or deleted). */
	missing: boolean,
};

/**  The repository list plus current selection. */
export type RepositoryList = {
	/**  Most recently opened first. */
	repositories: Repository[],
	selectedId: string | null,
};

/**  Changes Tenajlo saved when the user left a branch. */
export type SavedChanges = {
	branch: string,
};

/**  A reachable Forgejo (or Gitea-compatible) server. */
export type ServerInfo = {
	/**  Normalized address, e.g. `https://tmc-git01.tmus.local`. */
	baseUrl: string,
	version: string,
	/**  Where the user creates a personal access token. */
	tokenSettingsUrl: string,
	requiredScopes: string[],
};

/**  How much of a file's change is staged. */
export type StagedState = "None" | "Partial" | "Full";

/**  The sync button's action. */
export type SyncAction = 
/**  The repository has no remotes. */
{ type: "NoRemote" } | 
/**  The branch isn't on the server yet (no upstream, or it was deleted there). */
{ type: "Publish"; remote: string } | 
/**  The server has commits we don't (shown even if we also have new commits). */
{ type: "Pull"; remote: string } | { type: "Push"; remote: string } | { type: "Fetch"; remote: string };

/**  What the user clicked. Rust re-derives the details (remote, branch) itself. */
export type SyncRequest = "Fetch" | "Pull" | "Push" | "Publish";

/**  Sync button state for the current branch. */
export type SyncState = {
	action: SyncAction,
	branch: string | null,
	ahead: number,
	behind: number,
	/**  Unix seconds of the last fetch (FETCH_HEAD mtime), if any. */
	lastFetched: number | null,
};

/**  The message of an undone commit, so the UI can put it back in the commit box. */
export type UndoneCommit = {
	summary: string,
	description: string,
};

/**  Parsed working directory status. */
export type WorkingDirectoryStatus = {
	branch: BranchState,
	files: FileChange[],
	hasConflicts: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

