// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Locates git and reports its version and whether it meets the minimum. */
	checkGit: () => typedError<GitInfo, AppError>(__TAURI_INVOKE("check_git")),
	/**  Lists added repositories, most recently opened first. */
	listRepositories: () => __TAURI_INVOKE<RepositoryList>("list_repositories"),
	/**  Opens a folder picker and adds the chosen repository. `None` if the user cancelled. */
	addLocalRepository: () => typedError<{
	id: string,
	/**  Alias, or the folder name. */
	name: string,
	path: string,
	/**  The folder no longer exists (moved or deleted). */
	missing: boolean,
} | null, AppError>(__TAURI_INVOKE("add_local_repository")),
	/**  Removes a repository from the list. Files on disk are not touched. */
	removeRepository: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_repository", { id })),
	/**  Selects a repository and marks it recently opened. */
	selectRepository: (id: string) => typedError<Repository, AppError>(__TAURI_INVOKE("select_repository", { id })),
	/**  Working directory status for a repository. */
	getStatus: (repoId: string) => typedError<WorkingDirectoryStatus, AppError>(__TAURI_INVOKE("get_status", { repoId })),
	/**  Diff of a changed working-directory file. Unchanged if the file no longer has changes. */
	getWorkingDiff: (repoId: string, path: string) => typedError<FileDiff, AppError>(__TAURI_INVOKE("get_working_diff", { repoId, path })),
	/**  A page of commits reachable from HEAD, newest first. */
	getHistory: (repoId: string, skip: number, limit: number) => typedError<Commit[], AppError>(__TAURI_INVOKE("get_history", { repoId, skip, limit })),
	/**  Files changed by a commit. */
	getCommitFiles: (repoId: string, sha: string) => typedError<CommitFile[], AppError>(__TAURI_INVOKE("get_commit_files", { repoId, sha })),
	/**  Diff of one file within a commit. */
	getCommitDiff: (repoId: string, sha: string, path: string, oldPath: string | null) => typedError<FileDiff, AppError>(__TAURI_INVOKE("get_commit_diff", { repoId, sha, path, oldPath })),
	/**  Local and remote branches. */
	getBranches: (repoId: string) => typedError<BranchList, AppError>(__TAURI_INVOKE("get_branches", { repoId })),
	/**
	 *  Starts watching a repository for changes (emits `RepoChanged`). Replaces any previous watch.
	 *  Watching is best-effort: on failure the UI still refreshes on window focus.
	 */
	watchRepository: (repoId: string) => typedError<null, AppError>(__TAURI_INVOKE("watch_repository", { repoId })),
	/**  Whether the repository uses Git LFS and whether git-lfs is installed (for a warning). */
	getLfsStatus: (repoId: string) => typedError<LfsStatus, AppError>(__TAURI_INVOKE("get_lfs_status", { repoId })),
	/**  Stages (`staged = true`) or unstages the given changed files. */
	setStaged: (repoId: string, paths: string[], staged: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_staged", { repoId, paths, staged })),
	/**  Commits the staged changes. Returns the new commit's SHA. */
	commitChanges: (repoId: string, summary: string, description: string) => typedError<string, AppError>(__TAURI_INVOKE("commit_changes", { repoId, summary, description })),
	/**  The name and email git will record on commits in this repository. */
	getIdentity: (repoId: string) => typedError<Identity, AppError>(__TAURI_INVOKE("get_identity", { repoId })),
	/**
	 *  Saves name and email to the global git config. The UI calls this only after the user
	 *  explicitly confirms (CLAUDE.md rule 5).
	 */
	setGlobalIdentity: (name: string, email: string) => typedError<null, AppError>(__TAURI_INVOKE("set_global_identity", { name, email })),
	/**  Discards all changes to the given files. Current content goes to the OS trash first. */
	discardChanges: (repoId: string, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("discard_changes", { repoId, paths })),
	/**  Adds an untracked file (or all files with its extension) to the root `.gitignore`. */
	ignoreFile: (repoId: string, path: string, byExtension: boolean) => typedError<null, AppError>(__TAURI_INVOKE("ignore_file", { repoId, path, byExtension })),
	/**
	 *  Undoes the most recent commit if it is still `sha`, keeping its changes staged.
	 *  Returns the commit's message so the UI can restore it.
	 */
	undoCommit: (repoId: string, sha: string) => typedError<UndoneCommit, AppError>(__TAURI_INVOKE("undo_commit", { repoId, sha })),
	/**  Signed-in accounts (metadata only). */
	listAccounts: () => __TAURI_INVOKE<Account[]>("list_accounts"),
	/**  Checks that `server` is a reachable, trusted Forgejo server (sign-in step 2). */
	checkServer: (server: string) => typedError<ServerInfo, AppError>(__TAURI_INVOKE("check_server", { server })),
	/**  Verifies `token` with `GET /api/v1/user`, then saves the account and keychain entry. */
	signIn: (server: string, token: string) => typedError<Account, AppError>(__TAURI_INVOKE("sign_in", { server, token })),
	/**  Signs out: removes the account and deletes its token from the keychain. */
	signOut: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("sign_out", { id })),
	/**  Opens the server's "Applications" settings page, where the user creates a token. */
	openTokenSettings: (server: string) => typedError<null, AppError>(__TAURI_INVOKE("open_token_settings", { server })),
	/**  Repositories the account can clone: its own and its organizations'. */
	listForgejoRepositories: (accountId: string) => typedError<RemoteRepository[], AppError>(__TAURI_INVOKE("list_forgejo_repositories", { accountId })),
	/**
	 *  Default destination for `url`: `<default clone folder>/<name>` (Settings, else
	 *  `Documents/Tenajlo`), made unique if taken.
	 */
	suggestClonePath: (url: string) => typedError<string, AppError>(__TAURI_INVOKE("suggest_clone_path", { url })),
	/**  Lets the user pick a parent folder; returns `<picked>/<name>`, or `None` if cancelled. */
	chooseCloneFolder: (url: string) => typedError<string | null, AppError>(__TAURI_INVOKE("choose_clone_folder", { url })),
	/**
	 *  Clones `url` into `path`, then adds and selects the new repository. Progress arrives as
	 *  `GitProgress` events with an empty `repoId`; `cancel_operation(op_id)` stops it.
	 */
	cloneRepository: (opId: string, url: string, path: string) => typedError<Repository, AppError>(__TAURI_INVOKE("clone_repository", { opId, url, path })),
	/**  The merge (or rebase…) in progress and its conflicted files. */
	getOperationState: (repoId: string) => typedError<OperationState, AppError>(__TAURI_INVOKE("get_operation_state", { repoId })),
	/**  Marks conflicted files as resolved. Paths that aren't conflicted are ignored. */
	markResolved: (repoId: string, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("mark_resolved", { repoId, paths })),
	/**  Aborts the merge, rebase, cherry-pick or revert in progress. */
	abortOperation: (repoId: string) => typedError<null, AppError>(__TAURI_INVOKE("abort_operation", { repoId })),
	/**  Opens a repository file in the editor chosen in Settings (default: its default app). */
	openRepoFile: (repoId: string, path: string) => typedError<null, AppError>(__TAURI_INVOKE("open_repo_file", { repoId, path })),
	/**  Shows a repository file in Explorer / Finder / the file manager. */
	revealRepoFile: (repoId: string, path: string) => typedError<null, AppError>(__TAURI_INVOKE("reveal_repo_file", { repoId, path })),
	/**  Current settings. */
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	/**
	 *  Validates and saves settings; returns what was stored. After changing `gitPath`, the UI
	 *  re-runs `check_git`.
	 */
	saveSettings: (settings: Settings) => typedError<Settings, AppError>(__TAURI_INVOKE("save_settings", { settings })),
	/**  Folder picker for settings. `None` if cancelled. */
	chooseFolder: (title: string) => __TAURI_INVOKE<string | null>("choose_folder", { title }),
	/**  File picker for settings (git or editor program). `None` if cancelled. */
	chooseFile: (title: string) => __TAURI_INVOKE<string | null>("choose_file", { title }),
	/**  Name and email from the user's global git config. */
	getGlobalIdentity: () => typedError<Identity, AppError>(__TAURI_INVOKE("get_global_identity")),
	/**  Editors Settings can offer, and whether each is installed. */
	listEditors: () => __TAURI_INVOKE<EditorOption[]>("list_editors"),
	/**  Delivers the user's answer to a prompt (`None` = cancelled, which stops the operation). */
	answerAuthPrompt: (promptId: string, answer: {
	username: string | null,
	secret: string,
} | null) => __TAURI_INVOKE<void>("answer_auth_prompt", { promptId, answer }),
	/**  Cancels a running fetch, pull or push. Unknown ids are ignored. */
	cancelOperation: (opId: string) => __TAURI_INVOKE<void>("cancel_operation", { opId }),
	/**  The toolbar sync button state for the current branch. */
	getSyncState: (repoId: string) => typedError<SyncState, AppError>(__TAURI_INVOKE("get_sync_state", { repoId })),
	/**
	 *  Runs a fetch, pull, push or publish. `op_id` (a UUID from the UI) identifies its progress
	 *  events and lets `cancel_operation` stop it. `background` (the periodic fetch) never shows
	 *  sign-in prompts: without an account token or the user's own helper, it just fails.
	 */
	sync: (repoId: string, opId: string, request: SyncRequest, background: boolean) => typedError<null, AppError>(__TAURI_INVOKE("sync", { repoId, opId, request, background })),
	/**  How a typed branch name will be created (`"Fix pump"` → `"Fix-pump"`). Pure; no git call. */
	previewBranchName: (name: string) => __TAURI_INVOKE<string>("preview_branch_name", { name }),
	/**  Creates a branch from the current commit and switches to it. Local changes come along. */
	createBranch: (repoId: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("create_branch", { repoId, name })),
	/**  Switches to a local branch, or creates a tracking branch for a remote-only one. */
	switchBranch: (repoId: string, name: string, localChanges: LocalChanges) => typedError<null, AppError>(__TAURI_INVOKE("switch_branch", { repoId, name, localChanges })),
	/**  Deletes a local branch. Without `force`, fails with `BranchNotMerged` if it has unique commits. */
	deleteBranch: (repoId: string, name: string, force: boolean) => typedError<null, AppError>(__TAURI_INVOKE("delete_branch", { repoId, name, force })),
	/**  Changes Tenajlo saved when the user last left the current branch, if any. */
	getSavedChanges: (repoId: string) => typedError<{
	branch: string,
} | null, AppError>(__TAURI_INVOKE("get_saved_changes", { repoId })),
	/**  Re-applies the changes saved for the current branch. */
	restoreSavedChanges: (repoId: string) => typedError<null, AppError>(__TAURI_INVOKE("restore_saved_changes", { repoId })),
};

/** Events */
export const events = {
	authPromptRequested: makeEvent<AuthPromptRequested>("auth-prompt-requested"),
	gitProgress: makeEvent<GitProgress>("git-progress"),
	repoChanged: makeEvent<RepoChanged>("repo-changed"),
};

/* Types */
/**  Account metadata for the frontend. Never includes the token (CLAUDE.md rule 2). */
export type Account = {
	id: string,
	kind: AccountKind,
	baseUrl: string,
	login: string,
	displayName: string,
	avatarUrl: string | null,
	/**  The server stopped accepting the saved token; show "Sign in again". */
	needsSignIn: boolean,
};

/**  Kind of account. Only Forgejo for v1. */
export type AccountKind = "forgejo";

/**  Error shape sent to the frontend. Never contains secrets: `details` is redacted. */
export type AppError = {
	kind: AppErrorKind,
	/**  Set when `kind == Git`. */
	gitKind: GitErrorKind | null,
	/**  Plain-language message for non-Git-experts. */
	message: string,
	/**  Technical details shown behind "Details". */
	details: string | null,
	/**  The account this error is about (`SignInRequired`, account permission problems). */
	accountId: string | null,
};

/**  Broad category the UI uses to pick a dialog. */
export type AppErrorKind = "GitNotFound" | "GitUnsupported" | "GitTimedOut" | "GitCancelled" | "Git" | "UnknownRepository" | 
/**  A Forgejo server request failed (sign-in, repository list). */
"Server" | "UnknownAccount" | 
/**  The account's token no longer works; `account_id` says which. UI offers "Sign in again". */
"SignInRequired" | "Storage" | "InvalidInput" | "Internal";

/**  The user's answer. Flows UI → Rust only (CLAUDE.md rule 2). Debug output is redacted. */
export type AuthAnswer = {
	username: string | null,
	secret: string,
};

/**  Ask the user something on behalf of a running git operation. */
export type AuthPromptRequested = {
	promptId: string,
	repoId: string,
	opId: string,
	kind: PromptKind,
};

export type Branch = {
	/**  Short name: `main`, or `origin/main` for remote branches. */
	name: string,
	kind: BranchKind,
	/**  Remote name for remote branches. */
	remote: string | null,
	/**  Upstream (`origin/main`) for local branches that track one. */
	upstream: string | null,
	tip: string,
	isCurrent: boolean,
	/**  ISO 8601 date of the tip commit. */
	lastCommitDate: string,
};

export type BranchKind = "Local" | "Remote";

/**  Branches grouped the way the branch dropdown shows them. */
export type BranchList = {
	current: string | null,
	/**  Local branches, sorted by name (current included). */
	local: Branch[],
	/**  Remote branches with no local branch tracking them or sharing their name. */
	remoteOnly: Branch[],
};

/**  Branch information from `# branch.*` headers. */
export type BranchState = {
	/**  Current branch name; `None` when HEAD is detached. */
	name: string | null,
	/**  HEAD commit; `None` in a repository with no commits yet. */
	tip: string | null,
	upstream: string | null,
	ahead: number,
	behind: number,
	/**  An upstream is configured but no longer exists on the remote. */
	upstreamGone: boolean,
};

/**  One commit in the History list. */
export type Commit = {
	sha: string,
	shortSha: string,
	parents: string[],
	authorName: string,
	authorEmail: string,
	/**  Strict ISO 8601 with offset. */
	authorDate: string,
	summary: string,
	body: string,
};

/**  A file changed by a commit. */
export type CommitFile = {
	path: string,
	oldPath: string | null,
	kind: FileStatusKind,
};

/**  A conflicted file and how many conflict regions are still in it. */
export type ConflictedFile = {
	path: string,
	/**  `<<<<<<<` markers left; `None` for binary or very large files. */
	markers: number | null,
};

export type DiffHunk = {
	/**  The full `@@ … @@ section` header line. */
	header: string,
	lines: DiffLine[],
};

export type DiffLine = {
	kind: DiffLineKind,
	/**  Line content without the +/-/space marker or line ending. */
	text: string,
	oldLine: number | null,
	newLine: number | null,
	/**  Followed by "\ No newline at end of file". */
	noNewline: boolean,
};

export type DiffLineKind = "Context" | "Add" | "Delete";

/**  Program used for "Open in editor". */
export type Editor = 
/**  The file's default app. */
{ kind: "SystemDefault" } | { kind: "VsCode" } | { kind: "NotepadPlusPlus" } | { kind: "Custom"; path: string };

/**  An editor choice for the Settings list. */
export type EditorOption = {
	editor: Editor,
	label: string,
	/**  Found on this computer (always true for the system default and custom programs). */
	available: boolean,
};

/**  One changed path. */
export type FileChange = {
	/**  Repo-relative path, `/`-separated. */
	path: string,
	/**  Original path for renames and copies. */
	oldPath: string | null,
	kind: FileStatusKind,
	staged: StagedState,
	/**  The path is a submodule (detected and shown only; spec §2). */
	submodule: boolean,
};

/**  A file's diff, ready to render. */
export type FileDiff = { type: "Text"; hunks: DiffHunk[] } | { type: "Binary" } | { type: "TooLarge" } | 
/**  No content changes (e.g. only the file mode changed). */
{ type: "Unchanged" };

/**  What happened to a file, as shown in the Changes list. */
export type FileStatusKind = "Untracked" | "Added" | "Modified" | "Deleted" | "Renamed" | "Copied" | "Conflicted";

/**  Typed classification of a failed git invocation. */
export type GitErrorKind = "AuthFailed" | "HostKeyUnknown" | 
/**  The server's SSH host key differs from `known_hosts`: possibly an attack. */
"HostKeyChanged" | "SshKeyRejected" | "PushRejected" | "PullDiverged" | "LocalChangesBlock" | "TlsUntrusted" | "HostUnreachable" | "MergeConflict" | "NotARepository" | 
/**  Folder owned by another user; git's `safe.directory` check refused it. */
"DubiousOwnership" | 
/**  `user.name` / `user.email` not configured. */
"IdentityMissing" | "BranchExists" | "BranchNotMerged" | 
/**  The server has no such repository, or hides it from this account. */
"RepositoryNotFound" | "Unknown";

/**  Result of the startup git check, sent to the UI. */
export type GitInfo = {
	/**  Absolute path of the git executable in use. */
	path: string,
	version: GitVersion,
	minimum: GitVersion,
	/**  `version >= minimum`. */
	supported: boolean,
	/**  `git lfs version` output (e.g. `git-lfs/3.7.1 (…)`), or `None` if not installed. */
	lfsVersion: string | null,
};

/**  Progress of a running remote operation. */
export type GitProgress = {
	repoId: string,
	opId: string,
	progress: Progress,
};

/**  A git version triple. Vendor suffixes (`.windows.1`, `(Apple Git-154)`) are dropped. */
export type GitVersion = {
	major: number,
	minor: number,
	patch: number,
};

/**  Effective identity for a repository (local, then global config). */
export type Identity = {
	name: string | null,
	email: string | null,
};

/**  Whether a repository needs LFS and whether this computer has it. */
export type LfsStatus = {
	/**  `.gitattributes` routes files through the LFS filter, or `.lfsconfig` exists. */
	used: boolean,
	installed: boolean,
};

/**  What to do with uncommitted changes when switching (GitHub Desktop's two choices). */
export type LocalChanges = 
/**  Carry them to the target branch (fails if they would be overwritten). */
"Bring" | 
/**  Save them on the current branch and switch with a clean working directory. */
"Leave";

/**  A multi-step git operation that's waiting for the user. */
export type OperationKind = "Merge" | "Rebase" | "CherryPick" | "Revert";

/**  What the conflict banner shows. */
export type OperationState = {
	operation: OperationKind | null,
	conflicts: ConflictedFile[],
	/**  First line of git's prepared merge message, to prefill the commit summary. */
	mergeSummary: string | null,
};

/**  One progress update, e.g. `Receiving objects: 45% (450/1000)`. */
export type Progress = {
	/**  `Receiving objects`, `Resolving deltas`, `Writing objects`, … */
	phase: string,
	percent: number | null,
	/**  Remainder after the percentage, e.g. `(450/1000), 1.20 MiB | 2.00 MiB/s`. */
	detail: string | null,
	/**  Reported by the server (`remote:` prefix). */
	remote: boolean,
};

/**  A prompt shown to the user. Never carries secrets. */
export type PromptKind = 
/**  Username and password/token for an HTTPS host (one dialog for git's two prompts). */
{ type: "Credentials"; host: string } | 
/**  Password only; the username is already known (e.g. `https://evan@host/…`). */
{ type: "Password"; host: string; username: string } | 
/**  OpenSSH wants the passphrase for a private key. `retry` = an earlier answer was wrong. */
{ type: "Passphrase"; key: string; retry: boolean } | 
/**
 *  OpenSSH hasn't seen this server's host key. Accepting lets OpenSSH record it in
 *  `known_hosts` itself; Tenajlo never edits that file (CLAUDE.md rule 4).
 */
{ type: "HostKey"; host: string; key_type: string; fingerprint: string } | 
/**  Anything else git asks; shown verbatim. */
{ type: "Other"; prompt: string };

/**  What Pull does (spec §13.5: fast-forward only unless the user chooses otherwise). */
export type PullStrategy = 
/**  Fast-forward only; on divergence, offer a merge. */
"FastForwardOnly" | "Merge" | 
/**  No guided conflict UI: a conflicted rebase can only be aborted. */
"Rebase";

/**  A repository shown in the clone dialog. */
export type RemoteRepository = {
	/**  `owner/name`, unique per server. */
	fullName: string,
	owner: string,
	name: string,
	description: string,
	private: boolean,
	archived: boolean,
	/**  HTTPS clone URL. */
	cloneUrl: string,
	/**
	 *  SSH clone URL, with the server's SSH port (e.g. `ssh://git@host:2222/team/x.git`).
	 *  Empty if the server has SSH disabled.
	 */
	sshUrl: string,
};

/**  Emitted (debounced) when files or git state in a watched repository change. */
export type RepoChanged = {
	repoId: string,
};

/**  A repository as shown in the UI. */
export type Repository = {
	id: string,
	/**  Alias, or the folder name. */
	name: string,
	path: string,
	/**  The folder no longer exists (moved or deleted). */
	missing: boolean,
};

/**  The repository list plus current selection. */
export type RepositoryList = {
	/**  Most recently opened first. */
	repositories: Repository[],
	selectedId: string | null,
};

/**  Changes Tenajlo saved when the user left a branch. */
export type SavedChanges = {
	branch: string,
};

/**  A reachable Forgejo (or Gitea-compatible) server. */
export type ServerInfo = {
	/**  Normalized address, e.g. `https://tmc-git01.tmus.local`. */
	baseUrl: string,
	version: string,
	/**  Where the user creates a personal access token. */
	tokenSettingsUrl: string,
	requiredScopes: string[],
};

/**
 *  Contents of `settings.json`. Missing fields take their defaults (see `normalize`), so
 *  files written before a setting existed keep loading.
 */
export type Settings = {
	theme: Theme,
	/**  Where clones go by default; `None` = `Documents/Tenajlo`. */
	defaultCloneFolder: string | null,
	pullStrategy: PullStrategy,
	/**  0 = off. */
	backgroundFetchMinutes: number,
	/**  Git executable to use instead of the bundled/system one. */
	gitPath: string | null,
	editor: Editor,
};

/**  How much of a file's change is staged. */
export type StagedState = "None" | "Partial" | "Full";

/**  The sync button's action. */
export type SyncAction = 
/**  The repository has no remotes. */
{ type: "NoRemote" } | 
/**  The branch isn't on the server yet (no upstream, or it was deleted there). */
{ type: "Publish"; remote: string } | 
/**  The server has commits we don't (shown even if we also have new commits). */
{ type: "Pull"; remote: string } | { type: "Push"; remote: string } | { type: "Fetch"; remote: string };

/**  What the user clicked. Rust re-derives the details (remote, branch) itself. */
export type SyncRequest = "Fetch" | "Pull" | 
/**  "Merge the server's changes" after a fast-forward pull found diverged branches. */
"PullMerge" | "Push" | "Publish";

/**  Sync button state for the current branch. */
export type SyncState = {
	action: SyncAction,
	branch: string | null,
	ahead: number,
	behind: number,
	/**  Unix seconds of the last fetch (FETCH_HEAD mtime), if any. */
	lastFetched: number | null,
};

export type Theme = "System" | "Light" | "Dark";

/**  The message of an undone commit, so the UI can put it back in the commit box. */
export type UndoneCommit = {
	summary: string,
	description: string,
};

/**  Parsed working directory status. */
export type WorkingDirectoryStatus = {
	branch: BranchState,
	files: FileChange[],
	hasConflicts: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

