// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Locates git and reports its version and whether it meets the minimum. */
	checkGit: () => typedError<GitInfo, AppError>(__TAURI_INVOKE("check_git")),
};

/* Types */
/**  Error shape sent to the frontend. Never contains secrets: `details` is redacted. */
export type AppError = {
	kind: AppErrorKind,
	/**  Set when `kind == Git`. */
	gitKind: GitErrorKind | null,
	/**  Plain-language message for non-Git-experts. */
	message: string,
	/**  Technical details shown behind "Details". */
	details: string | null,
};

/**  Broad category the UI uses to pick a dialog. */
export type AppErrorKind = "GitNotFound" | "GitUnsupported" | "GitTimedOut" | "GitCancelled" | "Git" | "Internal";

/**  Typed classification of a failed git invocation. */
export type GitErrorKind = "AuthFailed" | "HostKeyUnknown" | "SshKeyRejected" | "PushRejected" | "PullDiverged" | "LocalChangesBlock" | "TlsUntrusted" | "HostUnreachable" | "MergeConflict" | "NotARepository" | "Unknown";

/**  Result of the startup git check, sent to the UI. */
export type GitInfo = {
	/**  Absolute path of the git executable in use. */
	path: string,
	version: GitVersion,
	minimum: GitVersion,
	/**  `version >= minimum`. */
	supported: boolean,
};

/**  A git version triple. Vendor suffixes (`.windows.1`, `(Apple Git-154)`) are dropped. */
export type GitVersion = {
	major: number,
	minor: number,
	patch: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

